### ISSUE TITLE
DYNAMIC_DRAW does not always work

### ISSUE THREAD

**Issue by thismarvin** [thismarvin/susurrus#5]
For some reason I keep getting this error:

GL_INVALID_OPERATION: Internal error: 0x00000502: Vertex buffer is not big enough for the draw call.

The only way to fix it is to changed the size that is allocated to the buffer by what seems like an arbitrary amount.

What is even weirder is that the problem does not exist with STATIC_DRAW

**Comment by thismarvin** [comment]
It has occurred to me that there seems to be a difference between Chrome and Firefox (and other browsers too). From initial testing, Firefox can get away with a smaller allocated size than Chrome before the error shows up?

At this point maybe just always using STATIC_DRAW is better?

**Comment by thismarvin** [comment]
I made it so DYNAMIC_DRAW used 4 times the minimum size, and that worked for a while, but it seems that once you ramp up the number of vertices then issue is back.

DYNAMIC_DRAW doesn't really do much, so for now I am going to just just STATIC_DRAW. However, I really wonder just how much extra you have to allocate for DYNAMIC_DRAW to work...

**Comment by thismarvin** [comment]
Just to be clear, the problem only affects the transformBuffer thing in polygon when it is set to VertexUsage.DYNAMIC.

Apparently if the length of the buffer is multiplied by the total amount of vertices the polygon has then DYNAMIC works fine? I am not sure if this is an instancing problem (i.e. a problem with my code) or an underlying problem with WebGL 1.

Anyway I will add a fix to the transformBuffer class to account for this. Still not sure if all of this is worth it just to use DYNAMIC, but hey whatever...

**Comment by thismarvin** [comment]
Alright so this whole problem only occurs on Chrome...

Firefox works fine. I guess i still need to check safari too 😒

**Comment by thismarvin** [comment]
For future reference:
https://stackoverflow.com/questions/16462517/bufferdata-usage-parameter-differences

**Comment by thismarvin** [comment]
It seems that this is a problem with the Blink engine.
I think it has to do with how instancing is handled behind the scenes? Again this problem is fixed if the size of the model is multiplied by the total amount of vertices.

For now i just made it so if the browser using Blink then the VertexUsage will always be STATIC.

**Comment by thismarvin** [comment]
I need to test this with safari but for now everything is good.

**Comment by gchoi17** [comment]
Thank you for this. I thought I was the only one having the problem and it drived me insane.
